### ISSUE TITLE
serp extension - add dropdown menu + 'speed settings' 

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/public#1]
# OVERVIEW

Video Explainer: https://www.loom.com/share/4179437ab0ad421d946ffc9d476cfd0d

---

Add a dropdown menu for the extension. 

Include 'speed settings' for MEDIUM + REDDIT, so the user can enter their own values (in milliseconds (ms)) into the inputs and when they click 'save' or whatever the button is, the values they choose will be used by the code.

Include a button to "Start" the action for medium.
Include a button to "Start" the action for reddit.

The three areas that can take user customized settings for speed for medium are:

- [ ] await new Promise(resolve => setTimeout(resolve, randomDelay(100, 400))); // Random delay between 50ms and 200ms
- [ ] await new Promise(resolve => setTimeout(resolve, randomDelay(500, 1500))); // Wait 0.5 to 1 second before next button
- [ ] await new Promise(resolve => setTimeout(resolve, 3000)); // Wait for 3 seconds

* you can look at the code for the available settings for reddit

# RESOURCES

- REPO: https://github.com/serpcompany/serp-extension

**Comment by devinschumacher** [comment]
Github Repo: https://github.com/serpcompany/serp-extension

**Comment by devinschumacher** [comment]
@mittalyashu how do i get the /approve to work?

**Comment by mittalyashu** [comment]
@devinschumacher Can you try it from the Alogra dashboard?

**Comment by devinschumacher** [comment]
@mittalyashu where? i cant find it in there

**Comment by mittalyashu** [comment]
> To reward a solution, navigate to your org page on Algora and locate the claim you'd like to pay out. Expand the claim to see the action buttons, and then click "Reward" to navigate to a Stripe page where you can enter your details and complete the payment.

From their help docs, https://docs.algora.io/bounties/workflow#pay-out-a-claim

**Comment by devinschumacher** [comment]
@mittalyashu did you add updates to the code after that loom video? the popup has additional stuff on it and funtions not the same as in the video - https://www.loom.com/share/5a31fc0e17b144e1a26baf1387a61bd5

**Comment by mittalyashu** [comment]
> did you add updates to the code after that loom video? the popup has additional stuff on it and funtions not the same as in the video

Yes, I have added the timer functionality for the Amazon platform. The reason I didn't included that in the loom video was that I wasn't exactly sure what does that logic do.

**Comment by zcesur** [comment]
Sorry about that folks, the bounty claim did not register earlier. I added it now and it can be paid out from [your bounty board](https://console.algora.io/org/SERP/bounties?status=open)

**Comment by mittalyashu** [comment]
Thanks a lot @zcesur for the help

**Comment by mittalyashu** [comment]
@devinschumacher can you try approving again for the dashboard?

**Comment by devinschumacher** [comment]
> > did you add updates to the code after that loom video? the popup has additional stuff on it and funtions not the same as in the video
> 
> Yes, I have added the timer functionality for the Amazon platform. The reason I didn't included that in the loom video was that I wasn't exactly sure what does that logic do.

@mittalyashu can you remove that please. there should be no timer on amazon and not setting area for it now, as it was not in the "todos". also it doesnt make any sense. keep the original amazon.js file in the extension but remove those additions you made please.
