### ISSUE TITLE
astro: force trailing slash `/` on all urls

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/public#10]
Need to edit the https://github.com/serpcompany/universityofguns.com repo built on astro so that it will automatically force/append a trailing slash `/` on any URL on the site, whether a link is clicked or directly entered into the browser bar.

---

Note: make sure you read & follow our "definition of done" to complete the todo successfully: https://github.com/serpcompany/public/discussions/8

**Comment by mittalyashu** [comment]
@devinschumacher On which platform have you deployed the site? Can you share the link of the live site?

**Comment by devinschumacher** [comment]
> @devinschumacher On which platform have you deployed the site? Can you share the link of the live site?

see the repo linked in og. task

**Comment by mittalyashu** [comment]
From what I have tested so far, the trailing slash is appearing on all sub pages. Except for the homepage.

**Comment by devinschumacher** [comment]
@mittalyashu did you make the changes or was it already doing that? i dont remember if i figured it out already and forgot to update this task or not

**Comment by mittalyashu** [comment]
> did you make the changes or was it already doing that? i dont remember if i figured it out already and forgot to update this task or not

No, I didn't made any changes for this issue.

> the trailing slash is appearing on all sub pages. Except for the homepage.

This is already working on the live site. 🙂

**Comment by devinschumacher** [comment]
@mittalyashu okay thanks for letting me know. i was working on it the other day and i thought i didnt get it but maybe i did!
