### ISSUE TITLE
reverse proxy: shop.daft.fm -> daft.fm/shop/

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/public#12]
📺 VIDEO EXPLAINER: https://www.loom.com/share/471ebbe379ff4816a015fae24dfe7eff

--- 

- [x] Want daft.fm/shop/ to show the content from shop.daft.fm
- [x] Make sure that daft.fm/shop forces trailing slash, ex: `daft.fm/shop/`
- [ ] shop.daft.fm to redirect to daft.fm/shop/

---

# DNS:

- `shop.daft.fm` = Cloudflare => CNAME @ serpcompany.github.io (Github Pages)
- `daft.fm` = Cloudflare => A @ IP ADDRESS (NGINX / Our server)

<img width="800" alt="image" src="https://github.com/serpcompany/public/assets/45643901/130d7893-c36e-41e7-996a-28655820cd6d">

---

# NGINX CONFIG (CURRENT):

```config

# SERVER CONFIGURATION daft.fm

server {
        # http -> redirect for daft.fm

        listen 80;
        listen [::]:80;
        server_name daft.fm www.daft.fm;

        return 301 https://daft.fm$request_uri;
}

server {
        # SSL configuration for daft.fm - https://www -> https:// redirect

        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        ssl_certificate            /etc/ssl/daft_fm_cert.pem;
        ssl_certificate_key        /etc/ssl/daft_fm_key.pem;
        ssl_client_certificate     /etc/ssl/cloudflare.crt;
        ssl_verify_client on;

        server_name www.daft.fm;

        return 301 https://daft.fm$request_uri;
}

server {
        # SSL configuration for daft.fm

        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        ssl_certificate            /etc/ssl/daft_fm_cert.pem;
        ssl_certificate_key        /etc/ssl/daft_fm_key.pem;
        ssl_client_certificate     /etc/ssl/cloudflare.crt;
        ssl_verify_client on;

        client_max_body_size 100M;

        server_name daft.fm;

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_hide_header Cache-Control;
                proxy_pass http://daft-fm;
        }

        # Redirect /shop to /shop/ to ensure the correct path is used
        location = /shop {
                return 301 https://daft.fm/shop/;
        }
        location = /shop/ {
                resolver 1.1.1.1;
                proxy_set_header Host shop.daft.fm;
                proxy_ssl_server_name on;
                proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                proxy_pass https://shop.daft.fm/;
        }
        location ~ ^/shop/(.*)$ {
                resolver 1.1.1.1;
                proxy_set_header Host shop.daft.fm;
                proxy_ssl_server_name on;
                proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                proxy_pass https://shop.daft.fm/shop/$1;
        }
        location ~ ^/_astro/(.*)$ {
                resolver 1.1.1.1;
                proxy_set_header Host shop.daft.fm;
                proxy_ssl_server_name on;
                proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                proxy_pass https://shop.daft.fm/_astro/$1;
        }

        location /static/ {
                # serve static files directly
                add_header X-Robots-Tag "noindex" always;
                autoindex off;
                alias /home/daftadmin/daft-fm/staticfiles/;
                expires max;
                access_log off;
        }

}

# end SERVER CONFIGURATION daft.fm
```

## OLD NOTES

i found my old notes from when i used to be able to do this with KINSTA (also NGINX)

i found my notes from back when i did this with kinsta (also nginx)

this is what i had to have them add:

```
location ^~ /courses/ {
proxy_pass https://courses.devinschumacher.com;
proxy_ssl_server_name on;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
```

```
location ^~ /static/ {
proxy_pass https://courses.devinschumacher.com/static/;
proxy_ssl_server_name on;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
```

^ does any of that give you an idea of how we get the shop.daft.fm to ---> daft.fm/shop/ ?

**Comment by jedi201321** [comment]
Hello, I think  the Nginx.conf is OK.

For the last task, u should change the shop.daft.fm of the Cloudflare Config.
Since I don't have a cloudfare account，I collected some information from the Internet.

You can try this configuration：
Rules -> Page Rules -> URL: shop.daft.fm/* Set to forward URL301 redirects to https://daft.fm/shop/$1

The name of the configuration page  may not be the ones I mentioned above,   Give it a try, though

**Comment by devinschumacher** [comment]
@jedi201321 i tried that but it creates an infinite redirect loop

**Comment by jedi201321** [comment]
What is the form of this loop？Does the browser keep opening new tabs？ or  you can see 500 httpcode in nginx error log.
Can you  show me the configuration you configured for shpp.daft.fm

**Comment by devinschumacher** [comment]
> What is the form of this loop？Does the browser keep opening new tabs？ or you can see 500 httpcode in nginx error log. Can you show me the configuration you configured for shpp.daft.fm

I included the configuration in that link in upwork.

the infinite loop does not open new tabs it just errors the window.

**Comment by devinschumacher** [comment]
@jedi201321 > What is the form of this loop？Does the browser keep opening new tabs？ or you can see 500 httpcode in nginx error log. Can you show me the configuration you configured for shpp.daft.fm

I included the configuration in that link in upwork.

the infinite loop does not open new tabs it just errors the window.

**Comment by jedi201321** [comment]
What I wanna see is the configuration of shop.daft.fm  the on   Cloudflare.
I am clear about the configuration of dns resolution, but not others.
When it errors the window, have you checked the request or status code in f12 of your browser?
Maybe these will give us some information.

**Comment by devinschumacher** [comment]
@jedi201321 i provided that information in the issue.

**Comment by jedi201321** [comment]
do you use  the Cloudflare for shop.daft.fm as  the  CDN ， or  only dns resolution?

**Comment by jedi201321** [comment]
> @jedi201321 i provided that information in the issue.

Can you show me a screenshot? Maybe we mean a different configuration

**Comment by devinschumacher** [comment]
<img width="857" alt="image" src="https://github.com/serpcompany/public/assets/45643901/31129858-508f-4bbd-a60a-7b1909d1c786">


@jedi201321

**Comment by jedi201321** [comment]
> @jedi201321 i tried that but it creates an infinite redirect loop

Can you show me how you configure it

**Comment by jedi201321** [comment]
I see that shop.daft.fm is Proxied   in the picture,   Is this a  L4(tcp) proxy  or a  L7(http) proxy ?

**Comment by devinschumacher** [comment]
@jedi201321 no idea its just the normal cloudflare A record to an IP address with the orange cloud on

**Comment by jedi201321** [comment]
if so,  maybe we should change  the github conf rather than Couldflare

**Comment by jedi201321** [comment]
can we change shop.daft.fm/index.html with  following content :
for example :
<script type="text/javascript">
  var hash = window.location.hash
  window.location.href = hash ? 'https://blog.liubasara.info' + '/' + hash : 'https://blog.liubasara.info'

**Comment by jedi201321** [comment]
did you try this method ?
https://www.process.st/templates/how-to-setup-a-cloudflare-dns-301-redirect-page-rules-url-forwarding/

**Comment by devinschumacher** [comment]
@jedi201321 you know im the one who wrote that right?

**Comment by jedi201321** [comment]
I'm afraid I didn't quite catch that

**Comment by devinschumacher** [comment]
resolved. 

i figured it out.

**Comment by jedi201321** [comment]
Which way is used

**Comment by devinschumacher** [comment]
I had to edit the nginx config, and some things in Astro and some things in cloudflare

**Comment by jedi201321** [comment]
OK，that's great.
would you mind give me some help at upwork?
