### ISSUE TITLE
Add new frontmatter fields for `metaRobots` & `seoTitle`

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/public#5]
## OVERVIEW:

Add a new frontmatter fields to the assigned astro site project/repo. 

Film a loom video doing the task, explaining what needs to be added/updated as you do it so that it can be turned into an SOP (or referenced by a junior developer later to follow along and complete the task without needing help).

- Frontmatter field: `metaRobots` & `seoTitle`

I need to be able to set some pages to "noindex", and want to have seoTitle in the frontmatter of the .md posts so that i can optimize the onpage SEO with more granularity

**Details:** 

A field where we can supply a string value (ex: "noindex, follow") that would render to HTML as the `<meta name="robots" content="noindex, follow">`

If none supplied, default to "index, follow".

## TASKS:

- [ ] add the two new frontmatter fields above & record a loom.com video showing the process so i can make it into an SOP

* Do your work on a BRANCH and submit a PR when done. include the loom.com video link in the PR

## RESOURCES:

- Repo: https://github.com/serpcompany/serp.media

**Comment by Bhavyajain21** [comment]
Can I be assigned? @devinschumacher

**Comment by mittalyashu** [comment]
@devinschumacher Can you mark this issue as completed and closed?

**Comment by devinschumacher** [comment]
> @devinschumacher Can you mark this issue as completed and closed?

Yes. sorry i thought algora would do that automatically (its my first time using it)

**Comment by devinschumacher** [comment]
completed.
